[package]
name = "wait-for-it"
version = "0.1.0"
authors = ["Watanabe Takashi <wtnb75@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.20.3"

[dev-dependencies]
cargo-cov = "0.0.5"
