on: [push]

name: rust

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install lcov
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: coverage
      run: |
        cargo install cargo-cov
        make -C rust coverage
        mkdir -p pages/rust/
        cp -a rust/target/cov/report/* pages/rust/
  golang:
    name: Golang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - run: |
        make -C go dep
        make -C go coverage
        mkdir -p pages/golang/
        cp -a go/cover.html pages/golang/index.html
  c:
    name: C
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install libcunit1-dev lcov
    - name: coverage
      run: |
        make -C c coverage-html
        mkdir -p pages/c/
        cp -a c/cover/* pages/c/
  cpp:
    name: C++
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install libcppunit-dev libgflags-dev libboost-dev lcov
    - name: coverage
      run: |
        make -C cpp coverage-html
        mkdir -p pages/cpp/
        cp -a cpp/cover/* pages/cpp/
  pages:
    name: upload coverage data
    needs: [c, cpp, rust, golang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: make index page
      run: |
        pip install dirindex
        dirindex make pages --template apache
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./pages
      with:
        forceOrphan: true
